# Generated by Django 4.0.2 on 2023-08-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_choose_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Escribe una Descripción'),
        ),
        migrations.AlterField(
            model_name='choose',
            name='heading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe una Razon'),
        ),
    ]
