# Generated by Django 4.0.2 on 2023-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='area_images', verbose_name='Subir Imagen del Area'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='definicion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Escribe una Definición'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='descriccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Escribe una Descripción corta'),
        ),
    ]
