# Generated by Django 4.0.2 on 2023-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_mision_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quienes_images', verbose_name='Suba imagen para Principios')),
                ('titulo', models.CharField(blank=True, default='Valores', max_length=50, null=True, verbose_name='Escribe un titulo para el Contenido')),
                ('parrafo1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe principio 1')),
                ('parrafo2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe principio 2')),
                ('parrafo3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe principio 3')),
                ('parrafo4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe principio 4')),
                ('parrafo5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe principio 5')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Principios',
                'verbose_name_plural': 'Principio',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quienes_images', verbose_name='Suba imagen para Valores')),
                ('titulo', models.CharField(blank=True, default='Valores', max_length=50, null=True, verbose_name='Escribe un titulo para el Contenido')),
                ('parrafo1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 1')),
                ('parrafo2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 2')),
                ('parrafo3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 3')),
                ('parrafo4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 4')),
                ('parrafo5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 5')),
                ('parrafo6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 6')),
                ('parrafo7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escribe valores 7')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Valores',
                'verbose_name_plural': 'Valores',
            },
        ),
    ]
