# Generated by Django 4.0.2 on 2023-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_principios_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipo_images', verbose_name='Subir imagen del equipo')),
                ('persona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe nombre del Abogado')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe una descipcion breve')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
