# Generated by Django 4.0.2 on 2023-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='descripcion2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
    ]
