# Generated by Django 4.0.2 on 2023-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_equipo_descripcion2_equipo_descripcion3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='descripcion8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe otra descripcion'),
        ),
    ]
