# Generated by Django 4.0.2 on 2023-08-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_equipo_descripcion8'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'area', 'verbose_name_plural': 'areas'},
        ),
        migrations.RenameField(
            model_name='areas',
            old_name='descriccion',
            new_name='descripcion',
        ),
    ]
