# Generated by Django 4.0.2 on 2023-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_remove_areas_class_name_imagen_areas_image_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='appointment_images', verbose_name='Suba una imagen para la sección')),
                ('heading_one', models.CharField(blank=True, default='Get a Appointment Today!', max_length=50, null=True, verbose_name='Escribir un titulo para la sección')),
                ('description_one', models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe una descripción para la sección')),
                ('heading_two', models.CharField(blank=True, default='We Are The Best Choice For Your Case', max_length=50, null=True, verbose_name='Escribir otro titulo para la sección')),
                ('description_two', models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe una descripción para la sección')),
                ('number', models.IntegerField(default=0, verbose_name='Introduce un numero de telefono')),
                ('check_point_one', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe primera caracteristica')),
                ('check_point_two', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe segunda caracteristica')),
                ('check_point_three', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe tercera caracteristica')),
                ('btn_text', models.CharField(blank=True, default='Obtener Cita', max_length=15, null=True, verbose_name='Escribe un texto para el boton cita')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
