# Generated by Django 4.0.2 on 2023-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_mensaje_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe una Razon')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Escribe una Descripción')),
                ('class_name', models.CharField(blank=True, default='icon-box-clr-1', max_length=50, null=True, verbose_name='')),
                ('class_name_icon', models.CharField(blank=True, default='fas fa-user-friends', max_length=50, null=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Razones',
                'verbose_name_plural': 'Razones',
            },
        ),
        migrations.DeleteModel(
            name='Choose',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Información de Contacto', 'verbose_name_plural': 'Información de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'ordering': ['timestamp'], 'verbose_name': 'Información de Contactos Usuarios', 'verbose_name_plural': 'Información de Contactos Usuarios'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=50, null=True, verbose_name='Ingrese Su dirección'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='call',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ingrese su numero de celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ingrese Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='support',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ingrese soporte Email'),
        ),
    ]
