# Generated by Django 4.0.2 on 2023-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_razones_delete_choose_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Celular')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha cita')),
                ('time', models.CharField(max_length=50, verbose_name='Hora cita')),
            ],
            options={
                'verbose_name': 'Información de Contactos con Solicitud de citas',
                'verbose_name_plural': 'Información de Contactos con Solicitud de citas',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Citas', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil usuario'},
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='btn_txt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Escribe texto para boton cita'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Suba una imagen'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_caption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribe un Mensjae para la imagen'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Escribe un Titulo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escribe un Mensaje'),
        ),
    ]
